cat > /tmp/install-proxy.sh <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

BIN_DIR="$HOME/bin"
ON="$BIN_DIR/proxy-on.sh"
OFF="$BIN_DIR/proxy-off.sh"
BASHRC="$HOME/.bashrc"
MARK_BEGIN="# >>> proxy on/off/status >>>"
MARK_END="# <<< proxy on/off/status <<<"

mkdir -p "$BIN_DIR"

# 1) 写 proxy-on.sh
cat > "$ON" <<'EOS'
#!/bin/bash
set -e

PORT=7890

WINIP=$(powershell.exe -Command "
Get-NetIPAddress -AddressFamily IPv4 |
Where-Object {
  \$_.InterfaceAlias -notmatch 'vEthernet' -and
  \$_.IPAddress -notlike '169.*'
} |
Select-Object -ExpandProperty IPAddress -First 1
" | tr -d '\r')

if [[ -z "$WINIP" ]]; then
  echo "[✘] 无法获取 Windows IPv4 地址（powershell.exe 返回为空）"
  return 1 2>/dev/null || exit 1
fi

PROXY="http://$WINIP:$PORT"

# Shell 代理（当前终端立即生效）
export http_proxy="$PROXY"
export https_proxy="$PROXY"
export all_proxy="$PROXY"

echo "[✔] Shell 代理已开启: $PROXY"

# VS Code WSL Server 代理（需 Reload WSL 才会进入 extensionHost）
cat > "$HOME/.vscode-server/server-env-setup" <<EOF
# Auto-generated by proxy-on.sh
export HTTP_PROXY="$PROXY"
export HTTPS_PROXY="$PROXY"
export ALL_PROXY="$PROXY"
export NO_PROXY="localhost,127.0.0.1,::1"
export NODE_OPTIONS="--dns-result-order=ipv4first"
EOF

echo "[✔] VS Code WSL 代理已开启（需 Reload WSL / 重连 VS Code）"
EOS

# 2) 写 proxy-off.sh
cat > "$OFF" <<'EOS'
#!/bin/bash
set -e

# Shell 代理（当前终端立即生效）
unset http_proxy https_proxy all_proxy
echo "[✘] Shell 代理已关闭"

# VS Code WSL Server 代理
VSCODE_ENV="$HOME/.vscode-server/server-env-setup"
if [ -f "$VSCODE_ENV" ]; then
  rm "$VSCODE_ENV"
  echo "[✘] VS Code WSL 代理已关闭（需 Reload WSL / 重连 VS Code）"
else
  echo "[ℹ] VS Code WSL 代理本来未开启"
fi
EOS

chmod +x "$ON" "$OFF"

# 3) 生成要写入 .bashrc 的函数块
read -r -d '' BLOCK <<EOS || true
$MARK_BEGIN
proxy() {
  case "\$1" in
    on)
      source "$ON"
      ;;
    off)
      source "$OFF"
      ;;
    status)
      echo "---- Shell Proxy ----"
      env | grep -i proxy || echo "(none)"
      echo
      echo "---- VS Code WSL Proxy ----"
      if [ -f "\$HOME/.vscode-server/server-env-setup" ]; then
        cat "\$HOME/.vscode-server/server-env-setup"
      else
        echo "(not set)"
      fi
      ;;
    *)
      echo "用法: proxy [on|off|status]"
      ;;
  esac
}
$MARK_END
EOS

# 4) 备份并写入（有标记则替换，无标记则追加）
cp "$BASHRC" "$BASHRC.bak.$(date +%Y%m%d_%H%M%S)"

if grep -qF "$MARK_BEGIN" "$BASHRC"; then
  # 删除旧标记块
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    $0==b {in=1; next}
    $0==e {in=0; next}
    !in {print}
  ' "$BASHRC" > "$BASHRC.tmp"
  mv "$BASHRC.tmp" "$BASHRC"
fi

# 追加新块
printf "\n%s\n" "$BLOCK" >> "$BASHRC"

echo "[✔] 已安装：$ON"
echo "[✔] 已安装：$OFF"
echo "[✔] 已写入：$BASHRC（并已备份一份 .bak.*）"
echo
echo "下一步：执行 source ~/.bashrc"
echo "然后你就可以用：proxy on | proxy off | proxy status"
EOF

bash /tmp/install-proxy.sh
