#!/usr/bin/env bash
set -euo pipefail

BIN_DIR="$HOME/bin"
ON="$BIN_DIR/proxy-on.sh"
OFF="$BIN_DIR/proxy-off.sh"
BASHRC="$HOME/.bashrc"
MARK_BEGIN="# >>> proxy on/off/status >>>"
MARK_END="# <<< proxy on/off/status <<<"

mkdir -p "$BIN_DIR"
touch "$BASHRC"

# 1) Write proxy-on.sh
cat > "$ON" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

PORT="${PORT:-7890}"

WINIP="$(powershell.exe -Command "
Get-NetIPAddress -AddressFamily IPv4 |
Where-Object {
  \$_.InterfaceAlias -notmatch 'vEthernet' -and
  \$_.IPAddress -notlike '169.*'
} |
Select-Object -ExpandProperty IPAddress -First 1
" | tr -d '\r')"

if [[ -z "$WINIP" ]]; then
  echo "[✘] Failed to get Windows IPv4 address (powershell.exe returned empty)."
  return 1 2>/dev/null || exit 1
fi

PROXY="http://${WINIP}:${PORT}"

# Shell proxy (takes effect immediately for current shell if sourced)
export http_proxy="$PROXY"
export https_proxy="$PROXY"
export all_proxy="$PROXY"

echo "[✔] Shell proxy enabled: $PROXY"

# VS Code Remote (WSL) proxy (takes effect after VS Code reload)
mkdir -p "$HOME/.vscode-server"
cat > "$HOME/.vscode-server/server-env-setup" <<EOF
# Auto-generated by proxy-on.sh
export HTTP_PROXY="$PROXY"
export HTTPS_PROXY="$PROXY"
export ALL_PROXY="$PROXY"
export NO_PROXY="localhost,127.0.0.1,::1"
export NODE_OPTIONS="--dns-result-order=ipv4first"
EOF

echo "[✔] VS Code WSL proxy enabled (reload VS Code / WSL window required)"
EOS

# 2) Write proxy-off.sh
cat > "$OFF" <<'EOS'
#!/usr/bin/env bash
set -euo pipefail

unset http_proxy https_proxy all_proxy
echo "[✘] Shell proxy disabled"

VSCODE_ENV="$HOME/.vscode-server/server-env-setup"
if [[ -f "$VSCODE_ENV" ]]; then
  rm -f "$VSCODE_ENV"
  echo "[✘] VS Code WSL proxy disabled (reload VS Code / WSL window required)"
else
  echo "[ℹ] VS Code WSL proxy was not set"
fi
EOS

chmod +x "$ON" "$OFF"

# 3) Generate the function block to be written into .bashrc (includes status)
read -r -d '' BLOCK <<EOS || true
$MARK_BEGIN

# Ensure ~/bin is on PATH (optional, but recommended)
case ":\$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) export PATH="$BIN_DIR:\$PATH" ;;
esac

proxy() {
  case "\$1" in
    on)
      # source to affect current shell env
      source "$ON"
      ;;
    off)
      source "$OFF"
      ;;
    status)
      echo "---- Shell Proxy ----"
      env | grep -i proxy || echo "(none)"
      echo
      echo "---- VS Code WSL Proxy ----"
      if [[ -f "\$HOME/.vscode-server/server-env-setup" ]]; then
        cat "\$HOME/.vscode-server/server-env-setup"
      else
        echo "(not set)"
      fi
      ;;
    *)
      echo "Usage: proxy {on|off|status}"
      ;;
  esac
}
$MARK_END
EOS

# 4) Backup and update .bashrc (replace marked block if it exists; otherwise append)
cp "$BASHRC" "$BASHRC.bak.$(date +%Y%m%d_%H%M%S)"

if grep -qF "$MARK_BEGIN" "$BASHRC"; then
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" '
    $0==b {in=1; next}
    $0==e {in=0; next}
    !in {print}
  ' "$BASHRC" > "$BASHRC.tmp"
  mv "$BASHRC.tmp" "$BASHRC"
fi

printf "\n%s\n" "$BLOCK" >> "$BASHRC"

echo "[✔] Installed: $ON"
echo "[✔] Installed: $OFF"
echo "[✔] Updated:   $BASHRC (backup created)"
echo
echo "Next:"
echo "  source ~/.bashrc"
echo "Then:"
echo "  proxy on | proxy off | proxy status"
